export const APP_TAGLINE = "Convierte PDF, PNG, JPG, JPEG y TIFF a CAD";
export const APP_DESCRIPTION =
  "Sube tu plano arquitectónico — escaneado, fotografiado o generado con IA — y obtén un archivo DXF/DWG editable con detección automática de muros, puertas, ventanas, habitaciones, textos y cotas.";

export const PLANS = [
  {
    id: "free",
    name: "Free",
    price: 0,
    paddlePriceId: "",
    description: "Para pruebas ocasionales",
    features: [
      "3 conversiones/mes",
      "50 MB de almacenamiento",
      "Exportación DXF",
      "Detección básica",
    ],
    cta: "Comenzar gratis",
    popular: false,
    conversions: "3/mes",
    storage: "50 MB",
    priority: false,
  },
  {
    id: "starter",
    name: "Starter",
    price: 15,
    paddlePriceId: "",
    description: "Para profesionales independientes",
    features: [
      "50 conversiones/mes",
      "1 GB de almacenamiento",
      "Exportación DXF",
      "Detección avanzada",
      "OCR de textos y cotas",
      "Soporte por email",
    ],
    cta: "Suscribirse",
    popular: false,
    conversions: "50/mes",
    storage: "1 GB",
    priority: false,
  },
  {
    id: "pro",
    name: "Pro",
    price: 35,
    paddlePriceId: "",
    description: "Para estudios y equipos pequeños",
    features: [
      "200 conversiones/mes",
      "5 GB de almacenamiento",
      "Exportación DXF + DWG",
      "Detección avanzada",
      "OCR de textos y cotas",
      "Procesamiento prioritario",
      "Soporte prioritario",
    ],
    cta: "Suscribirse",
    popular: true,
    conversions: "200/mes",
    storage: "5 GB",
    priority: true,
  },
  {
    id: "business",
    name: "Business",
    price: 60,
    paddlePriceId: "",
    description: "Para empresas con alto volumen",
    features: [
      "Conversiones ilimitadas",
      "25 GB de almacenamiento",
      "Exportación DXF + DWG",
      "Detección avanzada",
      "OCR de textos y cotas",
      "Procesamiento prioritario",
      "API dedicada",
      "Soporte dedicado 24/7",
    ],
    cta: "Suscribirse",
    popular: false,
    conversions: "Ilimitadas",
    storage: "25 GB",
    priority: true,
  },
] as const;
